#!/usr/bin/env python3
"""Convert an Intel HEX file into the `boot_program` SystemVerilog definition used by Day 99."""

import sys

BOOT_SIZE = 7680
DEFAULT_BYTE = 0xEA


def parse_hex(hex_file_path: str):
    memory = {}
    with open(hex_file_path, "r", encoding="utf-8") as f:
        extended_base = 0
        for line in f:
            line = line.strip()
            if not line.startswith(":"):
                continue

            byte_count = int(line[1:3], 16)
            address = int(line[3:7], 16) + extended_base
            record_type = int(line[7:9], 16)

            if record_type == 0:
                for i in range(byte_count):
                    memory[address + i] = int(line[9 + 2 * i : 11 + 2 * i], 16)
            elif record_type == 4:  # extended linear address
                extended_base = int(line[9:13], 16) << 16
    return memory


def hex_to_sv(hex_file_path: str):
    memory = parse_hex(hex_file_path)
    if not memory:
        raise SystemExit("No data found in HEX file.")

    start_addr = min(memory)
    end_addr = max(memory)
    length = end_addr - start_addr + 1

    if length > BOOT_SIZE:
        raise SystemExit(f"Boot program ({length} bytes) exceeds BOOT_SIZE ({BOOT_SIZE}).")

    print("// auto generated file")
    print(u"// this file has been generated by make in day10_completed")
    print(f"localparam logic [7:0] boot_program[{BOOT_SIZE}] = '{{")

    for idx in range(length):
        value = memory.get(start_addr + idx, DEFAULT_BYTE)
        print(f"        {idx}: 8'h{value:02X},")

    print(f"        default: 8'h{DEFAULT_BYTE:02X}")
    print("    };")
    print(f"localparam logic[15:0] boot_program_length = {length};")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python3 hex_to_sv.py <hex_file>")
        sys.exit(1)

    hex_to_sv(sys.argv[1])
