`include "cpu/state_boot.svinc"
`include "cpu/state_fetch.svinc"
`include "cpu/state_decode.svinc"
`include "cpu/state_write_req.svinc"
`include "cpu/state_show_info.svinc"
`include "cpu/state_clear_vram.svinc"
