// auto generated file
// this file has been generated by make in examples directory
localparam logic [7:0] boot_program[7680] = '{
        0: 8'hA9,
        1: 8'h41,
        2: 8'h8D,
        3: 8'h00,
        4: 8'hE0,
        5: 8'hA9,
        6: 8'h42,
        7: 8'h8D,
        8: 8'h01,
        9: 8'hE0,
        10: 8'hEF,
        default: 8'hEA
    };
localparam logic[15:0] boot_program_length = 11;
