// auto generated file
// this file has been generated by make in examples directory
// source: simple5.s
localparam logic [15:0] boot_program_length = 25;

function automatic logic [7:0] boot_program_byte(input logic [14:0] addr);
    case (addr)
    15'd0: boot_program_byte = 8'hA9;
    15'd1: boot_program_byte = 8'h20;
    15'd2: boot_program_byte = 8'hCF;
    15'd3: boot_program_byte = 8'h85;
    15'd4: boot_program_byte = 8'h01;
    15'd5: boot_program_byte = 8'h8D;
    15'd6: boot_program_byte = 8'h3B;
    15'd7: boot_program_byte = 8'hE0;
    15'd8: boot_program_byte = 8'hDF;
    15'd9: boot_program_byte = 8'h00;
    15'd10: boot_program_byte = 8'h00;
    15'd11: boot_program_byte = 8'hFF;
    15'd12: boot_program_byte = 8'h12;
    15'd13: boot_program_byte = 8'h18;
    15'd14: boot_program_byte = 8'h69;
    15'd15: boot_program_byte = 8'h01;
    15'd16: boot_program_byte = 8'hC9;
    15'd17: boot_program_byte = 8'h7F;
    15'd18: boot_program_byte = 8'hD0;
    15'd19: boot_program_byte = 8'hEE;
    15'd20: boot_program_byte = 8'hA9;
    15'd21: boot_program_byte = 8'h20;
    15'd22: boot_program_byte = 8'h4C;
    15'd23: boot_program_byte = 8'h02;
    15'd24: boot_program_byte = 8'h02;
    default: boot_program_byte = 8'hEA;
    endcase
endfunction
