// auto generated file
// this file has been generated by make in examples directory
localparam logic [7:0] boot_program[7680] = '{
        0: 8'hA9,
        1: 8'h41,
        2: 8'hCF,
        3: 8'h85,
        4: 8'h01,
        5: 8'h8D,
        6: 8'h3B,
        7: 8'hE0,
        8: 8'hDF,
        9: 8'h00,
        10: 8'h00,
        11: 8'hFF,
        12: 8'h74,
        13: 8'h18,
        14: 8'h69,
        15: 8'h01,
        16: 8'hC9,
        17: 8'h46,
        18: 8'hD0,
        19: 8'hEE,
        20: 8'hA9,
        21: 8'h41,
        22: 8'h4C,
        23: 8'h02,
        24: 8'h02,
        default: 8'hEA
    };
localparam logic[15:0] boot_program_length = 25;
